import type { Category, MenuItem, Review } from "./types";

export const CATEGORIES: Category[] = [
  { id: "recommend", label: "추천" },
  { id: "coffee", label: "커피" },
  { id: "non-coffee", label: "논커피" },
  { id: "tea", label: "티" },
  { id: "smoothie", label: "스무디" },
  { id: "ade", label: "에이드" },
  { id: "dessert", label: "디저트" },
  { id: "goods", label: "MD 굿즈" },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "americano",
    name: "브루리 아메리카노",
    description: "매일 아침 로스팅한 원두로 내린 시그니처 아메리카노",
    price: 4500,
    category: "coffee",
    emoji: "☕",
    tags: ["시그니처", "저칼로리"],
    rating: 4.8,
    reviewCount: 1204,
    isBest: true,
  },
  {
    id: "latte",
    name: "카페라떼",
    description: "고소한 우유와 에스프레소의 균형",
    price: 5000,
    category: "coffee",
    emoji: "🥛",
    tags: ["부드러움"],
    rating: 4.7,
    reviewCount: 982,
    isBest: true,
  },
  {
    id: "vanilla-latte",
    name: "바닐라 빈 라떼",
    description: "마다가스카르 바닐라빈을 그대로 갈아 넣은 라떼",
    price: 5800,
    category: "coffee",
    emoji: "🍦",
    tags: ["달콤"],
    rating: 4.6,
    reviewCount: 645,
  },
  {
    id: "cold-brew",
    name: "콜드브루",
    description: "18시간 저온 추출한 진한 풍미",
    price: 5300,
    category: "coffee",
    emoji: "🧊",
    tags: ["진한맛"],
    rating: 4.9,
    reviewCount: 1520,
    isBest: true,
  },
  {
    id: "einspanner",
    name: "아인슈페너",
    description: "부드러운 크림과 콜드브루의 조합",
    price: 6200,
    category: "coffee",
    emoji: "🍮",
    tags: ["크리미"],
    rating: 4.5,
    reviewCount: 411,
    isNew: true,
  },
  {
    id: "flat-white",
    name: "플랫화이트",
    description: "리스트레토 샷으로 진하게",
    price: 5500,
    category: "coffee",
    emoji: "☕",
    tags: ["진한맛"],
    rating: 4.4,
    reviewCount: 233,
  },
  {
    id: "choco",
    name: "다크 초콜릿 라떼",
    description: "카카오 72% 다크 초콜릿을 녹여 만든 라떼",
    price: 5800,
    category: "non-coffee",
    emoji: "🍫",
    tags: ["달콤"],
    rating: 4.6,
    reviewCount: 512,
  },
  {
    id: "milk-tea",
    name: "흑당 밀크티",
    description: "흑당 시럽과 아쌈 홍차의 만남",
    price: 6000,
    category: "non-coffee",
    emoji: "🧋",
    tags: ["달콤", "인기"],
    rating: 4.7,
    reviewCount: 733,
    isBest: true,
  },
  {
    id: "matcha",
    name: "말차 라떼",
    description: "우지 말차를 사용한 깊은 맛",
    price: 6200,
    category: "non-coffee",
    emoji: "🍵",
    tags: ["말차"],
    rating: 4.5,
    reviewCount: 388,
  },
  {
    id: "sweet-potato",
    name: "고구마 라떼",
    description: "국산 밤고구마를 그대로 갈아 넣은 라떼",
    price: 6000,
    category: "non-coffee",
    emoji: "🍠",
    tags: ["든든함"],
    rating: 4.3,
    reviewCount: 176,
  },
  {
    id: "earl-grey",
    name: "얼그레이 티",
    description: "베르가못 향이 은은한 홍차",
    price: 4800,
    category: "tea",
    emoji: "🫖",
    tags: ["카페인"],
    rating: 4.4,
    reviewCount: 210,
  },
  {
    id: "peppermint",
    name: "페퍼민트 티",
    description: "산뜻하게 마무리하기 좋은 허브티",
    price: 4800,
    category: "tea",
    emoji: "🌿",
    tags: ["카페인프리"],
    rating: 4.2,
    reviewCount: 143,
  },
  {
    id: "chamomile",
    name: "캐모마일 티",
    description: "잠들기 전에 어울리는 부드러운 향",
    price: 4800,
    category: "tea",
    emoji: "🌼",
    tags: ["카페인프리"],
    rating: 4.3,
    reviewCount: 98,
  },
  {
    id: "strawberry-smoothie",
    name: "딸기 스무디",
    description: "생딸기를 그대로 갈아 만든 스무디",
    price: 6500,
    category: "smoothie",
    emoji: "🍓",
    tags: ["과일"],
    rating: 4.8,
    reviewCount: 654,
    isBest: true,
  },
  {
    id: "mango-smoothie",
    name: "망고 스무디",
    description: "애플망고 과육이 씹히는 스무디",
    price: 6800,
    category: "smoothie",
    emoji: "🥭",
    tags: ["과일"],
    rating: 4.6,
    reviewCount: 421,
    isNew: true,
  },
  {
    id: "yogurt-smoothie",
    name: "플레인 요거트 스무디",
    description: "그릭요거트로 만든 꾸덕한 스무디",
    price: 6500,
    category: "smoothie",
    emoji: "🥤",
    tags: ["단백질"],
    rating: 4.4,
    reviewCount: 187,
  },
  {
    id: "lemon-ade",
    name: "레몬 에이드",
    description: "생레몬을 착즙한 상큼한 탄산",
    price: 5800,
    category: "ade",
    emoji: "🍋",
    tags: ["상큼"],
    rating: 4.5,
    reviewCount: 302,
  },
  {
    id: "grapefruit-ade",
    name: "자몽 에이드",
    description: "자몽 과육이 가득한 에이드",
    price: 6000,
    category: "ade",
    emoji: "🍊",
    tags: ["상큼"],
    rating: 4.6,
    reviewCount: 289,
  },
  {
    id: "blue-ade",
    name: "블루 하와이 에이드",
    description: "여름 한정 시원한 청량감",
    price: 6200,
    category: "ade",
    emoji: "🌊",
    tags: ["시즌한정"],
    rating: 4.1,
    reviewCount: 74,
    isNew: true,
  },
  {
    id: "croissant",
    name: "버터 크루아상",
    description: "결이 살아있는 프렌치 버터 크루아상",
    price: 4200,
    category: "dessert",
    emoji: "🥐",
    tags: ["베이커리"],
    rating: 4.7,
    reviewCount: 511,
    isBest: true,
  },
  {
    id: "cheese-cake",
    name: "바스크 치즈케이크",
    description: "겉은 진하게 속은 부드럽게 구워낸 케이크",
    price: 6800,
    category: "dessert",
    emoji: "🍰",
    tags: ["디저트"],
    rating: 4.8,
    reviewCount: 623,
  },
  {
    id: "cookie",
    name: "청크 초코 쿠키",
    description: "겉바속촉 두툼한 쿠키",
    price: 3800,
    category: "dessert",
    emoji: "🍪",
    tags: ["베이커리"],
    rating: 4.5,
    reviewCount: 340,
  },
  {
    id: "tiramisu",
    name: "티라미수",
    description: "마스카포네 크림을 층층이 쌓은 디저트",
    price: 7200,
    category: "dessert",
    emoji: "🧁",
    tags: ["디저트"],
    rating: 4.6,
    reviewCount: 265,
    isNew: true,
  },
  {
    id: "tumbler",
    name: "브루리 보온 텀블러",
    description: "473ml 스테인리스 보온 텀블러",
    price: 28000,
    category: "goods",
    emoji: "🥤",
    tags: ["MD"],
    rating: 4.9,
    reviewCount: 88,
  },
  {
    id: "mug",
    name: "시그니처 머그컵",
    description: "매장에서 쓰는 그 머그컵",
    price: 18000,
    category: "goods",
    emoji: "🍶",
    tags: ["MD"],
    rating: 4.7,
    reviewCount: 56,
  },
  {
    id: "drip-bag",
    name: "드립백 10개입",
    description: "집에서도 즐기는 브루리 원두",
    price: 15000,
    category: "goods",
    emoji: "📦",
    tags: ["MD", "선물"],
    rating: 4.8,
    reviewCount: 132,
  },
];

/** '추천' 카테고리는 별도 목록 없이 베스트/신메뉴로 구성 */
export function getMenuByCategory(category: string) {
  if (category === "recommend") {
    return MENU_ITEMS.filter((item) => item.isBest || item.isNew);
  }
  return MENU_ITEMS.filter((item) => item.category === category);
}

export function searchMenu(keyword: string) {
  const normalized = keyword.trim().toLowerCase();
  if (!normalized) return [];
  return MENU_ITEMS.filter(
    (item) =>
      item.name.toLowerCase().includes(normalized) ||
      item.description.toLowerCase().includes(normalized) ||
      item.tags.some((tag) => tag.toLowerCase().includes(normalized)),
  );
}

const REVIEW_AUTHORS = ["커피러버", "달콤한하루", "출근길", "라떼홀릭", "디저트요정", "얼죽아", "브루리단골", "오후세시", "카페인충전"];
const REVIEW_CONTENTS = [
  "산미가 적당해서 매일 마시기 좋아요. 얼음도 넉넉하게 주셔서 만족합니다.",
  "생각보다 양이 많아서 놀랐어요. 가격 대비 훌륭합니다!",
  "포장 상태가 깔끔했어요. 흘리지 않게 잘 담아주셔서 감사합니다.",
  "달달한 걸 좋아하면 무조건 추천합니다. 시럽 추가 없이도 충분해요.",
  "매장이 붐비는 시간인데도 주문이 빨리 나왔어요.",
  "향이 정말 좋아요. 다음엔 원두도 같이 사가려고요.",
  "아이스로 시켰는데 끝까지 안 밍밍해서 좋았습니다.",
  "직원분들이 친절하세요. 재방문 의사 100%!",
  "디저트랑 같이 먹으니 조합이 최고였어요.",
  "생각보다 진해서 저는 샷 하나 빼고 마셨어요.",
];

/** 데모용 리뷰 목록 (페이지네이션 확인을 위해 넉넉하게 생성) */
export const REVIEWS: Review[] = Array.from({ length: 47 }, (_, index) => {
  const menu = MENU_ITEMS[index % MENU_ITEMS.length];
  const day = 28 - (index % 28);
  return {
    id: `review-${index + 1}`,
    menuId: menu.id,
    menuName: menu.name,
    author: `${REVIEW_AUTHORS[index % REVIEW_AUTHORS.length]}${String(index + 1).padStart(2, "0")}`,
    rating: 3 + (index % 3) * 0.5 + (index % 2 === 0 ? 0.5 : 0),
    content: REVIEW_CONTENTS[index % REVIEW_CONTENTS.length],
    createdAt: `2026.07.${String(day).padStart(2, "0")}`,
  };
});
